#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_exe.py
============

Compile ramp_optimizer.py into a native GUI executable (rampa.exe on
Windows, ./rampa on Linux/Mac) using PyInstaller.

Author: Efren Rodriguez Rodriguez
Web:    https://efrenrodriguezrodriguez.com/

Usage
-----

    Windows   ->  open cmd or PowerShell here and run:
                      python build_exe.py
                  Result: dist\\rampa.exe   (English UI by default)

    Spanish UI version:
                      python build_exe.py --spanish
                      (or  --es  for short)
                  Result: dist\\rampa.exe   (Spanish UI)

    Linux/Mac ->  python3 build_exe.py [--spanish]
                  Result: dist/rampa

What it does
------------
1. Checks that numpy, scipy, matplotlib and pyinstaller are installed;
   pip-installs them if missing.
2. Cleans previous builds (build/, dist/, rampa.spec).
3. If --spanish is given, drops a marker file `_lang_es.flag` next to
   the script and bundles it into the .exe via PyInstaller's
   --add-data.  At runtime the executable detects the marker and
   switches the UI / output files to Spanish.
4. Calls PyInstaller with the right flags:
     --onefile      -> single self-contained executable
     --windowed     -> no console window (we ship a Tkinter GUI)
     --hidden-import matplotlib.backends.backend_pdf  (and
                     backend_agg, backend_svg) so matplotlib can write
                     PDF / PNG / SVG inside the bundled .exe
     --hidden-import tkinter*  in case PyInstaller does not detect them
     --collect-submodules scipy / matplotlib.backends
     --collect-data matplotlib
5. Verifies the executable was created and prints a short usage hint.

The resulting executable launches the GUI by default.  Calling it with
command-line arguments (e.g. `rampa.exe 136 540`) runs the silent mode
that just produces the blueprints without opening the GUI.
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

REQUIRED_PACKAGES = ["numpy", "scipy", "matplotlib", "pyinstaller"]

PROJECT_DIR = Path(__file__).resolve().parent
SCRIPT = PROJECT_DIR / "ramp_optimizer.py"
LANG_FLAG_FILE = PROJECT_DIR / "_lang_es.flag"
ICON_FILE = PROJECT_DIR / "docs" / "icon.ico"
LOCALE_DIR = PROJECT_DIR / "locale"
PYPROJECT = PROJECT_DIR / "pyproject.toml"
VERSION_FILE = PROJECT_DIR / "_version_info.txt"


def run(cmd, **kw):
    print(">>>", " ".join(str(c) for c in cmd))
    return subprocess.check_call(cmd, **kw)


def ensure_package(pkg_name: str, import_name: str | None = None) -> None:
    """pip-install *pkg_name* if it is not importable."""
    name_for_import = import_name or pkg_name
    try:
        __import__(name_for_import)
        print(f"OK  {pkg_name} is already installed.")
        return
    except ImportError:
        pass
    print(f"... installing {pkg_name} ...")
    run([sys.executable, "-m", "pip", "install", "--upgrade", pkg_name])


def read_project_version() -> str:
    """Pull the project version out of ``pyproject.toml``.

    Used to label the bundled .exe with matching ``FileVersion`` /
    ``ProductVersion`` strings (visible in Windows Explorer's
    Properties dialog and consulted by Microsoft Defender's
    reputation system).  Falls back to ``"0.0.0"`` if anything goes
    wrong so a missing field never blocks the build.
    """
    if not PYPROJECT.exists():
        return "0.0.0"
    try:
        # tomllib is stdlib in 3.11+, tomli is the back-port for 3.10.
        try:
            import tomllib  # type: ignore[import-not-found]
        except ModuleNotFoundError:
            import tomli as tomllib  # type: ignore[no-redef]
        with PYPROJECT.open("rb") as f:
            data = tomllib.load(f)
        return str(data.get("project", {}).get("version", "0.0.0"))
    except Exception as exc:  # noqa: BLE001
        print(f"WARN: could not read pyproject.toml version ({exc}); "
              f"using 0.0.0.")
        return "0.0.0"


def write_version_file(target: Path, version: str, spanish: bool) -> None:
    """Write a Windows VS_VERSION_INFO file for PyInstaller's ``--version-file``.

    Embedding this metadata gives the .exe a real "Properties" tab
    in Explorer and helps Microsoft Defender / SmartScreen build
    reputation across releases (an unsigned but versioned binary
    fares slightly better than an unsigned, unversioned one).

    See:
      https://pyinstaller.org/en/stable/usage.html#capturing-windows-version-data
    """
    parts = [int(n) for n in (version.split("-")[0].split(".") + ["0"] * 4)][:4]
    a, b, c, d = parts
    label_suffix = " (Spanish)" if spanish else ""
    fname = "rampa.exe"
    body = f"""# UTF-8 -- generated by build_exe.py, do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, {d}),
    prodvers=({a}, {b}, {c}, {d}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [
          StringStruct(u'CompanyName',      u'Efren Rodriguez Rodriguez'),
          StringStruct(u'FileDescription',  u'Garage Ramp Optimizer{label_suffix}'),
          StringStruct(u'FileVersion',      u'{a}.{b}.{c}.{d}'),
          StringStruct(u'InternalName',     u'rampa'),
          StringStruct(u'LegalCopyright',   u'Copyright (c) 2026 Efren Rodriguez Rodriguez'),
          StringStruct(u'OriginalFilename', u'{fname}'),
          StringStruct(u'ProductName',      u'Garage Ramp Optimizer'),
          StringStruct(u'ProductVersion',   u'{a}.{b}.{c}.{d}'),
        ]
      )
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    target.write_text(body, encoding="utf-8")


def rebuild_pyinstaller_bootloader() -> None:
    """Force PyInstaller to (re)compile its bootloader from source.

    The PyPI wheel ships a prebuilt bootloader whose byte signature
    is already in many antivirus heuristic databases -- which is the
    main reason a freshly built `.exe` from a clean environment is
    flagged as "suspicious" by Microsoft Defender, BitDefender,
    Avast, and friends.  Rebuilding the bootloader from source on
    your own machine usually clears the false positives because the
    resulting bytes have not been seen by the AV heuristics.

    Requires a C compiler on PATH (Visual Studio Build Tools on
    Windows, gcc/clang elsewhere).  The reinstall is idempotent --
    pip is a no-op when the wheel is already source-built.
    """
    print("... rebuilding PyInstaller bootloader from source "
          "(needs a C compiler) ...")
    run([
        sys.executable, "-m", "pip", "install",
        "--upgrade", "--force-reinstall",
        "--no-binary", ":all:",
        "pyinstaller",
    ])


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="build_exe",
        description="Compile ramp_optimizer.py into a native GUI executable. "
                    "Pass --spanish to bundle a Spanish UI.",
    )
    p.add_argument(
        "--spanish", "--es", dest="spanish", action="store_true",
        help="Build the Spanish version of the GUI and the output blueprints.",
    )
    p.add_argument(
        "--rebuild-bootloader",
        dest="rebuild_bootloader", action="store_true",
        help=(
            "Reinstall PyInstaller from source so its bootloader "
            "is compiled locally.  Helps reduce antivirus false "
            "positives.  Requires a C compiler on PATH (Visual "
            "Studio Build Tools on Windows, gcc/clang elsewhere)."
        ),
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    print("=" * 70)
    print("  Garage ramp optimizer - build script")
    print("=" * 70)
    print(f"  System      : {platform.system()} {platform.release()}")
    print(f"  Python      : {sys.version.split()[0]}")
    print(f"  Folder      : {PROJECT_DIR}")
    print(f"  Language    : {'Spanish (es)' if args.spanish else 'English (en)'}")
    print()

    if not SCRIPT.exists():
        print(f"ERROR: cannot find {SCRIPT}", file=sys.stderr)
        sys.exit(1)

    # 1) Ensure dependencies.
    print("Step 1: ensuring required dependencies are installed...")
    # Install everything from requirements.txt so the pinned scipy
    # range (and any other version constraints) are honored on local
    # builds, not just on the GitHub Actions release pipeline.  We
    # still call ``ensure_package`` afterwards as a belt-and-braces
    # check that imports succeed before the PyInstaller step.
    requirements_file = PROJECT_DIR / "requirements.txt"
    if requirements_file.exists():
        print(f"... installing pinned versions from {requirements_file} ...")
        run([
            sys.executable, "-m", "pip", "install",
            "--upgrade", "-r", str(requirements_file),
        ])
    ensure_package("numpy")
    ensure_package("scipy")
    ensure_package("matplotlib")
    ensure_package("pyinstaller", import_name="PyInstaller")
    if args.rebuild_bootloader:
        rebuild_pyinstaller_bootloader()
    print()

    # 2) Clean previous builds.
    print("Step 2: cleaning previous builds...")
    for d in ("build", "dist"):
        target = PROJECT_DIR / d
        if target.exists():
            shutil.rmtree(target, ignore_errors=True)
    spec_file = PROJECT_DIR / "rampa.spec"
    if spec_file.exists():
        spec_file.unlink()
    # Drop or recreate the language marker file.
    if LANG_FLAG_FILE.exists():
        LANG_FLAG_FILE.unlink()
    if VERSION_FILE.exists():
        VERSION_FILE.unlink()
    print()

    # 2b) Generate the Windows VS_VERSION_INFO file.  Embedding it
    # gives the .exe a populated Properties dialog (Company,
    # File / Product version, Description) and helps SmartScreen /
    # Defender reputation slowly build across releases.
    project_version = read_project_version()
    write_version_file(VERSION_FILE, project_version, args.spanish)
    print(f"  Embedded version : {project_version}")
    print()

    # 3) Run PyInstaller.
    print("Step 3: building with PyInstaller "
          "(this may take a couple of minutes)...")

    sep = ";" if platform.system() == "Windows" else ":"
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",                  # single self-contained .exe
        "--windowed",                 # no console window (it is a GUI)
        "--name", "rampa",
        "--noconfirm",
        "--clean",
        # scipy loads some modules dynamically; this flag makes sure
        # PyInstaller bundles them all.  We explicitly enumerate the
        # matplotlib backends we use further below instead of relying
        # on ``--collect-submodules matplotlib.backends``: that crawl
        # pulls in every Qt / GTK / wx backend matplotlib ships and
        # then fires a noisy "no Qt bindings are available" warning,
        # even though we never use any of those backends.
        "--collect-submodules", "scipy",
        "--collect-data", "matplotlib",
        # Specific backends.  Without these matplotlib's lazy import of
        # backend_pdf would fail at runtime.  backend_tkagg is needed by
        # the GUI's live linear-ramp preview canvas.
        "--hidden-import", "matplotlib.backends.backend_pdf",
        "--hidden-import", "matplotlib.backends.backend_agg",
        "--hidden-import", "matplotlib.backends.backend_svg",
        "--hidden-import", "matplotlib.backends.backend_tkagg",
        # Tkinter ships with Python but some PyInstaller versions still
        # need it spelled out.
        "--hidden-import", "tkinter",
        "--hidden-import", "tkinter.ttk",
        "--hidden-import", "tkinter.filedialog",
        "--hidden-import", "tkinter.messagebox",
        # Drop modules that PyInstaller's stale hooks reference but the
        # installed packages no longer ship, plus heavyweight optional
        # backends (PyTorch, Qt, GTK, wx, macOS) that we never use.
        # Each --exclude-module silences a corresponding WARNING in the
        # build log without touching runtime behaviour.
        "--exclude-module", "torch",
        "--exclude-module", "scipy._lib.array_api_compat.torch",
        "--exclude-module", "scipy.special._cdflib",
        "--exclude-module", "PyQt5",
        "--exclude-module", "PyQt6",
        "--exclude-module", "PySide2",
        "--exclude-module", "PySide6",
        "--exclude-module", "matplotlib.backends.qt_compat",
        "--exclude-module", "matplotlib.backends.qt_editor",
        "--exclude-module", "matplotlib.backends.backend_qt",
        "--exclude-module", "matplotlib.backends.backend_qtagg",
        "--exclude-module", "matplotlib.backends.backend_qtcairo",
        "--exclude-module", "matplotlib.backends.backend_qt5",
        "--exclude-module", "matplotlib.backends.backend_qt5agg",
        "--exclude-module", "matplotlib.backends.backend_qt5cairo",
        "--exclude-module", "matplotlib.backends.backend_gtk3",
        "--exclude-module", "matplotlib.backends.backend_gtk3agg",
        "--exclude-module", "matplotlib.backends.backend_gtk3cairo",
        "--exclude-module", "matplotlib.backends.backend_gtk4",
        "--exclude-module", "matplotlib.backends.backend_gtk4agg",
        "--exclude-module", "matplotlib.backends.backend_gtk4cairo",
        "--exclude-module", "matplotlib.backends.backend_wx",
        "--exclude-module", "matplotlib.backends.backend_wxagg",
        "--exclude-module", "matplotlib.backends.backend_wxcairo",
        "--exclude-module", "matplotlib.backends.backend_macosx",
        "--exclude-module", "matplotlib.backends.backend_nbagg",
    ]

    # Custom application icon, when present (only matters on Windows
    # / macOS; PyInstaller silently ignores it on Linux .onefile builds).
    if ICON_FILE.exists():
        cmd += ["--icon", str(ICON_FILE)]

    # Embedded VS_VERSION_INFO so Explorer's Properties dialog shows
    # the real version / company / file description.  PyInstaller
    # silently ignores --version-file on non-Windows builds.
    if VERSION_FILE.exists():
        cmd += ["--version-file", str(VERSION_FILE)]

    # Bundle the gettext catalog so the Spanish UI can use the standard
    # gettext path at runtime (with the in-process dict as fallback).
    # The catalog is generated by ``scripts/sync_translations.py``.
    if LOCALE_DIR.is_dir():
        cmd += ["--add-data", f"{LOCALE_DIR}{sep}locale"]

    if args.spanish:
        # Create the marker file and bundle it.  ramp_optimizer.py looks
        # for it inside sys._MEIPASS at startup and switches LANGUAGE to
        # 'es' when present.
        LANG_FLAG_FILE.write_text("es", encoding="utf-8")
        cmd += ["--add-data", f"{LANG_FLAG_FILE}{sep}."]

    cmd.append(str(SCRIPT))

    try:
        run(cmd, cwd=PROJECT_DIR)
    except subprocess.CalledProcessError as e:
        print(f"\nERROR: PyInstaller failed with exit code {e.returncode}.",
              file=sys.stderr)
        sys.exit(e.returncode)
    finally:
        # Marker is bundled inside the .exe; we can remove it from the
        # source tree to keep things clean.
        if LANG_FLAG_FILE.exists():
            try:
                LANG_FLAG_FILE.unlink()
            except OSError:
                pass
        # Same for the auto-generated VS_VERSION_INFO file: it lives
        # only long enough for PyInstaller to read it.
        if VERSION_FILE.exists():
            try:
                VERSION_FILE.unlink()
            except OSError:
                pass

    # 4) Verify result.
    is_windows = platform.system() == "Windows"
    out_name = "rampa.exe" if is_windows else "rampa"
    out_path = PROJECT_DIR / "dist" / out_name
    print()
    if not out_path.exists():
        print(f"ERROR: did not create {out_path}", file=sys.stderr)
        sys.exit(1)

    size_mb = out_path.stat().st_size / (1024 * 1024)
    print("=" * 70)
    lang_tag = " [Spanish UI]" if args.spanish else " [English UI]"
    print(f"  OK. Executable created{lang_tag}:")
    print(f"    {out_path}   ({size_mb:.1f} MB)")
    print("=" * 70)
    print()
    print("Usage:")
    if is_windows:
        print(r"  - Double-click dist\rampa.exe   -> opens the GUI.")
        print(r"  - From cmd:   dist\rampa.exe 136 540   "
              r"(silent mode, just generates the blueprints).")
    else:
        print("  - ./dist/rampa            -> opens the GUI.")
        print("  - ./dist/rampa 136 540    (silent mode).")
    print()


if __name__ == "__main__":
    main()
