"""Tests for the localization layer."""

import pytest

import ramp_optimizer as ro


def test_default_language_is_english():
    # When the test suite runs there is no _lang_es.flag, no
    # RAMP_LANG=es and the binary is not frozen, so the default must
    # be English.
    assert ro.LANGUAGE == "en"


def test_t_passes_through_when_english():
    ro._set_language("en")
    assert ro.t("Garage Ramp Optimizer") == "Garage Ramp Optimizer"


def test_t_returns_spanish_when_language_is_es():
    ro._set_language("es")
    try:
        assert ro.t("Garage Ramp Optimizer") == "Optimizador de Rampa de Garaje"
        assert ro.t("Ramp data") == "Datos de la rampa"
        assert ro.t("Calculate and generate blueprints") == \
            "Calcular y generar planos"
    finally:
        ro._set_language("en")


def test_t_falls_back_to_input_for_unknown_keys():
    ro._set_language("es")
    try:
        assert ro.t("a string that is not in the translation dictionary") == \
            "a string that is not in the translation dictionary"
    finally:
        ro._set_language("en")


def test_translation_dict_has_no_empty_values():
    """Spot-check that we did not commit empty string mappings."""
    d = ro._TRANSLATIONS_ES
    empty = [k for k, v in d.items() if not v]
    assert not empty, f"empty translations for: {empty}"


def test_gettext_catalog_roundtrips_when_present():
    """If the compiled gettext catalog exists, it must agree with the
    in-process dict for every string we know how to translate.

    The catalog is generated by scripts/sync_translations.py; if it is
    not present (e.g. on a fresh clone before that script has been
    run), we just skip.
    """
    import gettext as _gettext
    from pathlib import Path

    locale_dir = Path(__file__).resolve().parent.parent / "locale"
    if not (locale_dir / "es" / "LC_MESSAGES" / "ramp_optimizer.mo").is_file():
        pytest.skip("gettext catalog not generated yet")

    tr = _gettext.translation(
        "ramp_optimizer", localedir=str(locale_dir), languages=["es"],
    )
    samples = [
        "Garage Ramp Optimizer",
        "Ramp data",
        "Calculate and generate blueprints",
        "Garage floor (flat)",
    ]
    for s in samples:
        assert tr.gettext(s) == ro._TRANSLATIONS_ES[s], (
            f"catalog and dict disagree for {s!r}"
        )
